Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "ouseqqamS" do |ouseqqamS|
		ouseqqamS.vm.provider "virtualbox" do |v|
			v.name = "ouseqqamS"
			v.memory = 1024
  			v.cpus = 1
		end
		ouseqqamS.vm.hostname = "ouseqqamS"
		ouseqqamS.vm.network "private_network", ip: "192.168.42.110"
		ouseqqamS.vm.provision "shell", path: "create.sh"
	end
end